### ISSUE TITLE
Problem With Using the FVVDP Metric for Scaled Images

### ISSUE THREAD

**Issue by miklesz** [gfxdisp/FovVideoVDP#13]
I'm trying to use the FVVDP metric for comparing identical images but scaled down and up again. Of course, it's not about comparing images with different resolutions - each image scaled down is scaled back to its original size.
While the scale maximum (reference) is always at the level of 10.0, the scale minimum can vary greatly depending on the source image. The worst possible image we can get is an image with a real resolution of 1x1, then stretched to the size of the original, which is really a solid color for the entire screen. We might expect that since the maximum quality is 10.0, the minimum quality will be something around 0.0. And indeed, for example, for the picture below (let's call it "People_157_h.png", because that's the name in my collection), which in the original looks like this:
![People_157_h_A](https://user-images.githubusercontent.com/14861745/219399118-6022c6c5-bdfd-4dff-a73f-f2c134c47c7f.png)
an image enlarged from a 1x1 resolution has a metric value of 0.4966745302, which is quite close to 0.0.
But for another image, let's call it "People_160_h.png", which originally looks like this:
![People_160_h_A](https://user-images.githubusercontent.com/14861745/219399339-d4745240-d3b0-459a-b76c-562ce8038415.png)
its 1x1 metric is 4.941684362. The picture itself then looks like this:
![People_160_h_G](https://user-images.githubusercontent.com/14861745/219399426-ce4d2dda-c318-4678-8e70-09e33d4d390f.png)
and this solid color actually represents the original quite well.
The problem is that I would expect a given quality level to have identical metric levels. Meanwhile, at the metric level of quality 4.941684362, the "People_157_h.png" image looks like this:
![People_157_h_G](https://user-images.githubusercontent.com/14861745/219399604-063abcb3-16c5-49ab-976b-827d1d2901a6.png)
Well, I don't know about you, but I have the impression that this is quite good quality for the image "People_157_h.png", because in the end you can see something there (do an experiment and move a few meters away from the screen - suddenly you will see quite a lot). So something is probably not right.
Or maybe differently, the two images below, according to the FVVDP metric, have the same quality, equal to 0.4966745302 (on a scale of 10.0):
![People_160_h_G](https://user-images.githubusercontent.com/14861745/219399706-b8ccdbdf-ea19-4110-81e6-81e9f41dbb4d.png)
![People_157_h_G](https://user-images.githubusercontent.com/14861745/219399930-54c771de-7b42-4356-a13b-6413dfd4e80f.png)
So I would like to raise a question, why is this happening?

**Comment by achapiro** [comment]
Hi miklesz!

I think the confusion stems from how you are interpreting the score of the metric. Although the "best" score is scaled to 10, there's no "worst" score in our case. Each unit of difference is counted as 1 just-objectionable-difference (JOD), which is a type of unit used in psychophysics, closely related to the just-noticeable-difference and standard deviation concepts.

In our paper manuscript (https://achapiro.github.io/Man21/mantiuk2021_VideoVDP.pdf), formula 19 in Sec. 3.9 is how we compute the score. You can see it is just given by (10-D), where D is the difference between test and reference in JODs. So e.g. a score of 9 is really 1 JOD away from the reference, and a score of 10 means the images are identical. There's no special significance to a score of 0, and in principle you could even end up with negative scores, although much like a standard deviation having a score that large is not very meaningful (unless it's for some sort of progression of distortions).

The result you got makes decent sense to me - both images are extremely far away from the reference (~9.5 JODs away), but given the differences in the original images a blurry version of the flowers may be roughly as "bad" as a gray field for the skier. If you want to learn more about JOD scales, our manuscript and the GitHub documentations are probably the best resources.

I hope this clears it up!

Best,
Alex.

**Comment by achapiro** [comment]
P.S.: Note that our metric also takes into account the geometry of the display in relation to the user, including the distance, so "stepping away" from the display to see a sharper picture is not a good test - it does change the way you perceive the image. We have several templates to help you get started with defining display geometry and photometry. I hope this helps!

**Comment by mantiuk** [comment]
To add to what Alex said and to explain why the metric performs as it does in your example: FovVideoVDP assesses quality based on the perceived contrast difference between the test and reference images. Because your first reference image has a lot of contrast everywhere, while the second image with the snowboarder has much less contrast overall, it takes much less contrast change for the metric to lower the quality score on the first image than on the second. 

The metric does not contain any logic or ML model to account for the fact that something can be seen in the first distorted image but nothing is seen in the second. A non-reference metric could probably do a better job in this scenario. 

Another issue is that there are not many datasets with such high levels of distortion and quality metrics are rarely calibrated on those.

**Comment by miklesz** [comment]
Thank you for all the information provided.
