### ISSUE TITLE
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 1, 720, 1280, 7]

### ISSUE THREAD

**Issue by Spark001** [gfxdisp/FovVideoVDP#3]
Hi,

When I try your example script, I got a error about "conv1d".

`python fvvdp_run.py --gpu 0 --ref ../pytorch_examples/aliasing/ferris-ref.mp4 --test ../pytorch_examples/aliasing/ferris-bicubic-bicubic.mp4 --display "sdr_fhd_24" --heatmap supra-threshold` 

the detailed output :
```
[INFO] Running on device: cuda:0
[INFO] Mode: Video
[INFO] Using color space sRGB
[INFO] When reporting metric results, please include the following information:
[INFO] FovVideoVDP v1.0, 37.8 [pix/deg], Lpeak=100, Lblack=0.4979 [cd/m^2], non-foveated
[INFO] Predicting the quality for ../pytorch_examples/aliasing/ferris-bicubic-bicubic.mp4...
    SSIM 0.7560 Traceback (most recent call last):
  File "fvvdp_run.py", line 236, in <module>
    loss, jod, diff_map = vdploss(display_model.get_luminance_pytorch(test_vid[:,:,0:cur_frames,...]), ref_vid_luminance[:,:,0:cur_frames,...])
  File "/root/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/bfs/FovVideoVDP/pytorch/fvvdp.py", line 487, in forward
    return self.compute_metric(output, target)
  File "/bfs/FovVideoVDP/pytorch/fvvdp.py", line 589, in compute_metric
    R[:,cc*2+0, :, :, :] = Func.conv1d(sw_buf[0].permute(0,1,3,4,2), corr_filter, padding=0).permute(0,1,4,2,3)
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 1, 720, 1280, 7]
```

Then I read the code, I found there is a "correlation" operator. So I change it to be like 
```
R[0,cc*2+0, :, :, :] = (sw_buf[0].permute(0,1,3,4,2)* corr_filter).sum(dim=-1,keepdim=True).permute(0,1,4,2,3)
R[0,cc*2+1, :, :, :] = (sw_buf[1].permute(0,1,3,4,2)* corr_filter).sum(dim=-1,keepdim=True).permute(0,1,4,2,3)
```

Unfortunatly, I got different JOD value from yours:

```
[INFO] FovVideoVDP v1.0, 37.8 [pix/deg], Lpeak=100, Lblack=0.4979 [cd/m^2], non-foveated
[INFO] Predicting the quality for ../pytorch_examples/aliasing/ferris-bicubic-bicubic.mp4...
    SSIM 0.7560 Q_JOD=7.1878
[INFO] Writing heat maps...
[INFO] Predicting the quality for ../pytorch_examples/aliasing/ferris-bicubic-nearest.mp4...
    SSIM 0.7058 Q_JOD=7.0068
[INFO] Writing heat maps...
[INFO] Predicting the quality for ../pytorch_examples/aliasing/ferris-nearest-bicubic.mp4...
    SSIM 0.7645 Q_JOD=6.4451
[INFO] Writing heat maps...
[INFO] Predicting the quality for ../pytorch_examples/aliasing/ferris-nearest-nearest.mp4...
    SSIM 0.7199 Q_JOD=6.3233
```
Any suggestion are appreciated. TAT

**Comment by mantiuk** [comment]
This is strange. The code runs without any errors on PyTorch '1.10.0.dev20210911'.
Could you please report here `torch.__version__`? 

But regardless of that, your change makes perfect sense - no convolution is needed. I further simplified the code to avoid permuting dimensions (which should make the code faster). Please check the latest commit and tell us whether it works for you.

The reported Q_JOD values should be correct. Embarrassingly, the values in the README.md were for the pre-release version and we forgot to update those. Those should be correct now. 

Are you on the latest commit of the `main` branch? The latest version should not report SSIM values.

**Comment by Spark001** [comment]
@mantiuk sorry for the late reply.
At that time, my pytorch version is 1.10.1.

It's identical when I check the results between mine with your latest results.

It works well that you remove the permutation operations.

By the way, I'm on the `main` branch at that time . I modified the code to report SSIM values because I want to align your number in the README.
