### ISSUE TITLE
Runtime error: unexpected keyword "models_file" for class method "load"

### ISSUE THREAD

**Issue by JoshuaEbenezer** [gfxdisp/FovVideoVDP#9]
I get a runtime error because the keyword "models_file" is not defined for the class method "load" in line 52 of  fvvdp_display_model.py. Removing it fixes the issue because "models_file" is defined inside the method anyway in line 53.

**Comment by mantiuk** [comment]
I do not see "models_file" in https://github.com/gfxdisp/FovVideoVDP/blob/188f0e9fe2f687d1edd50c5a85a808b731b34347/pyfvvdp/fvvdp_display_model.py#L52

Please pull the latest commit.

**Comment by JoshuaEbenezer** [comment]
Hi Rafael

Yes, it looks like it's been fixed! I shall pull the latest commit. Thanks!

Regards
Josh
